# Generated by Django 4.1.13 on 2026-06-04 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la mission')),
                ('description', models.TextField(verbose_name='Description du besoin')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget estimé')),
                ('skills_required', models.CharField(help_text='Séparez par des virgules', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
