# Generated by Django 4.1.13 on 2026-06-15 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0002_mission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='contracts.mission'),
        ),
        migrations.AddField(
            model_name='application',
            name='proposed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarif proposé'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(verbose_name="Message d'accroche / Motivation"),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('mission', 'freelance')},
        ),
        migrations.RemoveField(
            model_name='application',
            name='bid_amount',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
