# Generated by Django 4.1.13 on 2026-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_application_options_application_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite'),
        ),
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('filled', 'Pourvue'), ('cancelled', 'Annulée')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('long', 'Long terme')], default='normal', max_length=20),
        ),
    ]
