# Generated by Django 6.0.5 on 2026-06-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_mission_deadline_mission_status_mission_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='category',
            field=models.CharField(choices=[('Developpement Web', 'Développement Web'), ('Design', 'Design'), ('Marketing Digital', 'Marketing Digital'), ('Redaction', 'Rédaction'), ('Video', 'Vidéo'), ('Traduction', 'Traduction'), ('Cybersecurite', 'Cybersécurité'), ('IA', 'Intelligence Artificielle')], default='Developpement Web', max_length=50),
        ),
        migrations.AddField(
            model_name='mission',
            name='currency',
            field=models.CharField(choices=[('EUR', '€ EUR'), ('USD', '$ USD'), ('GBP', '£ GBP'), ('XOF', 'FCFA XOF')], default='EUR', max_length=5),
        ),
        migrations.AddField(
            model_name='mission',
            name='duration',
            field=models.CharField(choices=[('1-7 jours', '1-7 jours'), ('1-2 semaines', '1-2 semaines'), ('1 mois', '1 mois'), ('1-3 mois', '1-3 mois'), ('3-6 mois', '3-6 mois'), ('6+ mois', '6+ mois')], default='1 mois', max_length=20),
        ),
        migrations.AddField(
            model_name='mission',
            name='extra_info',
            field=models.TextField(blank=True, verbose_name='Infos supplémentaires'),
        ),
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.CharField(choices=[('Teletravail', 'Télétravail'), ('Paris', 'Paris'), ('Lyon', 'Lyon'), ('Marseille', 'Marseille'), ('Bordeaux', 'Bordeaux'), ('Lille', 'Lille'), ('Toulouse', 'Toulouse'), ('Nantes', 'Nantes'), ('Nice', 'Nice'), ('Strasbourg', 'Strasbourg')], default='Teletravail', max_length=50),
        ),
        migrations.AddField(
            model_name='mission',
            name='payment_type',
            field=models.CharField(choices=[('fixed', 'Forfait'), ('hourly', "À l'heure"), ('daily', 'À la journée')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('in-progress', 'En cours'), ('closed', 'Terminée'), ('cancelled', 'Annulée')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='urgency',
            field=models.CharField(choices=[('low', 'Normal'), ('medium', 'Moyen'), ('high', 'Urgent')], default='low', max_length=20),
        ),
    ]
