# Generated by Django 4.1.13 on 2026-06-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_application_status_alter_application_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='budget_type',
            field=models.CharField(choices=[('fixed', 'Budget fixe'), ('negotiable', 'À discuter')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget estimé'),
        ),
    ]
