# Generated by Django 4.1.13 on 2026-06-29 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0007_mission_budget_type_alter_mission_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='Entreprise du client')),
                ('client_address', models.TextField(blank=True, verbose_name='Adresse du client')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone du client')),
                ('description', models.TextField(verbose_name='Description de la prestation')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant HT')),
                ('tva', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='TVA (%)')),
                ('freelance_company', models.CharField(blank=True, max_length=200, verbose_name='Nom de votre entreprise')),
                ('freelance_address', models.TextField(blank=True, verbose_name='Votre adresse')),
                ('freelance_phone', models.CharField(blank=True, max_length=50, verbose_name='Votre téléphone')),
                ('freelance_siret', models.CharField(blank=True, max_length=50, verbose_name='N° SIRET / Registre de commerce')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('terms', models.TextField(blank=True, default='Paiement à réception sous 30 jours', verbose_name='Conditions de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes supplémentaires')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Banque')),
                ('bank_iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('bank_bic', models.CharField(blank=True, max_length=50, verbose_name='BIC/SWIFT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.application')),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contracts.mission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
