# Generated by Django 4.1.13 on 2026-06-29 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0008_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('description', models.TextField(verbose_name='Description de la prestation')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant estimé HT')),
                ('tva', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='TVA (%)')),
                ('freelance_company', models.CharField(blank=True, max_length=200, verbose_name='Votre entreprise')),
                ('freelance_phone', models.CharField(blank=True, max_length=50, verbose_name='Votre téléphone')),
                ('freelance_address', models.TextField(blank=True, verbose_name='Votre adresse')),
                ('freelance_siret', models.CharField(blank=True, max_length=50, verbose_name='N° SIRET / RC')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Validité du devis')),
                ('terms', models.TextField(blank=True, default='Devis valable 30 jours', verbose_name='Conditions')),
                ('notes', models.TextField(blank=True, verbose_name='Notes supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='contracts.application')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_received', to=settings.AUTH_USER_MODEL)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_sent', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='contracts.mission')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
