# Generated by Django 4.1.13 on 2026-06-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set(),
        ),
    ]
