# Generated by Django 4.1.13 on 2026-06-25 10:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_fix_chat_message_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together={('client', 'freelance')},
        ),
    ]
