# Generated by Django 4.1.13 on 2026-06-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clientprofile_id_alter_freelanceprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceprofile',
            name='skills',
            field=models.CharField(help_text='compétences séparées par des virgules', max_length=250),
        ),
    ]
