# Generated by Django 4.1.13 on 2026-06-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contactmessage_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='auto_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='font_size',
            field=models.CharField(default='Normale', max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='language',
            field=models.CharField(default='Français', max_length=20),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='min_budget',
            field=models.CharField(default='Aucun', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='notif_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='notif_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='notif_missions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='notif_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='notif_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_categories',
            field=models.CharField(default='Toutes', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='share_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='theme',
            field=models.CharField(default='Clair', max_length=20),
        ),
    ]
