# Generated by Django 4.1.13 on 2026-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_freelanceprofile_auto_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceprofile',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior'), ('intermediate', 'Intermédiaire'), ('senior', 'Senior')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='freelanceprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
    ]
