# Generated by Django 4.1.13 on 2026-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CMD-FREELANCE', max_length=100)),
                ('site_description', models.TextField(blank=True, default='Plateforme de mise en relation freelances et clients')),
                ('support_email', models.EmailField(default='support@cmd-freelance.com', max_length=254)),
                ('default_currency', models.CharField(default='FCFA', max_length=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission plateforme en %', max_digits=5)),
                ('min_payout', models.DecimalField(decimal_places=2, default=5000, help_text='Montant minimum de retrait (FCFA)', max_digits=12)),
                ('max_payout', models.DecimalField(decimal_places=2, default=5000000, help_text='Montant maximum de retrait (FCFA)', max_digits=12)),
                ('enable_registrations', models.BooleanField(default=True, verbose_name='Activer les inscriptions')),
                ('auto_validate_freelances', models.BooleanField(default=False, verbose_name='Valider automatiquement les freelances')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('notif_new_user', models.BooleanField(default=True, verbose_name='Nouvelle inscription')),
                ('notif_new_mission', models.BooleanField(default=True, verbose_name='Nouvelle mission')),
                ('notif_payment', models.BooleanField(default=True, verbose_name='Paiement reçu')),
                ('notif_dispute', models.BooleanField(default=True, verbose_name='Nouveau litige')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('meta_keywords', models.CharField(blank=True, default='', max_length=300)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres plateforme',
                'verbose_name_plural': 'Paramètres plateforme',
            },
        ),
    ]
