# Generated by Django 6.0.5 on 2026-06-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_freelanceprofile_cv_freelanceprofile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
