# Generated by Django 6.0.5 on 2026-06-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_document_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('orange', 'Orange Money'), ('wave', 'Wave'), ('mtn', 'MTN Mobile Money'), ('stripe', 'Carte bancaire'), ('bank', 'Virement bancaire'), ('wallet', 'Portefeuille SMD-Tech'), ('test', 'TEST (simulation)')], max_length=20),
        ),
    ]
